version: '3'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/promtail.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "Admin123"
    volumes:
      - ./grafana-storage:/var/lib/grafana

  nodejs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      NODE_ENV: production
    logging:
      driver: loki
      options:
        loki-url: "http://51.20.109.17:3100/loki/api/v1/push"
        loki-batch-size: 100
        loki-batch-wait: 1s
    depends_on:
      - promtail


